### ISSUE TITLE
unclear origins and author RIP

### ISSUE THREAD

**Issue by stsp** [stsp/comcom32#12]
This comcom32 seems to have unclear origins:
https://sourceforge.net/p/freedos-32/mailman/message/3995213/
```
From what I remember, the source for this program has been sent to the
freedos mailing list by the original author
```
Contrary to what is said here, I can't find this post by an author.
And very unfortunately we can't contact an author, as he died.
https://www.legacy.com/obituaries/centredaily/obituary.aspx?n=Allen-S.Cheung&pid=181402633

So the only hope is if someone who googles better than
me, can find the original source code dump.

**Comment by stsp** [comment]
https://sourceforge.net/p/freedos-32/mailman/message/3995210/
Seems like FreeDOS have removed all the traces of it,
and who knows why? :(

**Comment by keithdennison** [comment]
Hello,

I am the lead software engineer at Centroid Corp. The author who has passed away (Allen Cheung) was a former co-worker of mine. I am aware of the email sent to Centroid Corp. inquiring about the copyright that Allen had placed into one or more FreeDOS related files.

We are interested in helping you out, but want to make sure that Allen did not post any files that were not FreeDOS related. If this is the case, please let me know and we (Centroid Corp.) will work it out with you. If you have other files that are copyright by Centroid Corp. that are not related to the FreeDOS project, then we would of course want to review those files.

**Comment by stsp** [comment]
Hello and thanks for the very quick reply!
I sent the request just today. :)

The only file I have that is copyrighted by Centroid Corp,
is this one:
https://github.com/stsp/comcom32/blob/master/command.c
The thing is, I was not involved in the dump itself,
which happened around year 2000.
If there were more files that were dumped, then they
were removed and have not survived till now - rumours
says the leak was removed from the freedos servers
very quickly (likely someone from the company have
contacted them). Google finds no origins of it, so I really
hope there is nothing to worry about on your side about
any other files.
Also I wouldn't be using any non-freedos related files
anyway, since my goal is only in retro-computing.
So if you really need a more accurate info about the
original leak (rather than just my use of one particular
file), you can reach Jim Hall of freedos. But if google
finds nothing, the chances are good there is really nothing
else.

> inquiring about the copyright that Allen had placed into one or more FreeDOS related files.

Yes, the first thing to find out is whether Allen himself
have put the GPL copyright, or someone else did after
the leak happened. If that was Allen's initiative, then the
only remaining question is whether it can remain so and
be distributed under that license forever. This can be so
in 2 scenarios:
1. Allen did the copyright assignment legally. Then only
the confirmation would be good that it was so, as I can't
find any origins.
2. Allen did that illegally (to help the free software community!),
and you may want to "re-release" this code under the terms of
GNU GPL v3+, or any other license that you think suits.

Of course my hope is that, after 20+ years have passed and
the author have passed away, you will not treat that project
as illegal and cease it existence.

Thanks!

**Comment by stsp** [comment]
@keithdennison 
It would be quite upsetting if this issue to remain
unresolved. While, on one hand, this may implicitly
mean I can continue the work on the project under
the GNU GPL license terms, on the other hand this
may bring problems submitting this software to the
free software distributions, like Debian or Fedora.
The sign that you became aware of the code dump,
may not be enough for them.
So just one word of confirmation, like
"Yes, you have the right to distribute that code
under GNU GPL v3+ license" will really help.
And yes, I am going to put this software to all the
popular linux distributions, so this may also be
good as some PR for your company. For example
I can make the copyrights more visible (displayed
at start-up) etc, if this will help you to take a decision.

Thank you.

**Comment by keithdennison** [comment]
Stas,

Yes, you have the right to distribute the code (
https://github.com/stsp/comcom32/blob/master/command.c) under GNU GPL v3+
license.

Regards,

Keith Dennison
Centroid Corp.
Lead Software Engineer

**Comment by stsp** [comment]
Thank you very much!
I'll make sure Allen's (and your company) contribution
will not be forgotten in the retro-computing world.

**Comment by stsp** [comment]
I added the appropriate copyright headings to the file
in question, https://github.com/stsp/comcom32/commit/087c7aa151ae3c7d485a89cc90c3ccbbe5afc691
