### ISSUE TITLE
package djgpp for ubuntu

### ISSUE THREAD

**Issue by stsp** [stsp/comcom32#15]
Currently I upload pre-built comcom32 binary
to git, which is not very good. Needs to integrate
djgpp build with launchpad. The best candidate looks
this one:
https://github.com/jwt27/build-gcc
Just needs to test whether DESTDIR works here
and write debuild boiler-plate.

**Comment by mikhailnov** [comment]
What is djpp?

**Comment by stsp** [comment]
https://en.wikipedia.org/wiki/DJGPP
