### ISSUE TITLE
cyrillic р doesn't work

### ISSUE THREAD

**Issue by stsp** [stsp/comcom32#24]
With `$_internal_char_set = "cp866"` cyrillic `р`
doesn't work.

**Comment by tkchia** [comment]
Is there any known reason why the routine was checking for `0xe0` in the first place?

(As far as I know `getch ()` from `<conio.h>` should not ever use `0xe0` to signify an extended key code.  `int $0x16` functions `0x10` and `0x11` however might do that.)

Thank you!

**Comment by stsp** [comment]
No idea why it was coded that way.
And I don't think any extended key code
is specified for `getch()`, but it returns 0
as such indication, as my testing suggests.
