### ISSUE TITLE
NWClient VLM.EXE causes FDPP crash 

### ISSUE THREAD

**Issue by andrewbird** [stsp/comcom32#27]
I'm attempting to get the Netware Client running over IPX so that I can observe its interaction with the redirector, but I'm having a problem. Firstly this is my first ever experience with IPX so I could be doing it all wrong of course, but I doubt that FDPP crashing should be the result of that. Here's what I have:

- Tap interface
~~~
root@polly:~# ip tuntap list
virbr0-nic: tap UNKNOWN_FLAGS:800
tap0: tap UNKNOWN_FLAGS:800 user 500
~~~

- Virtual Ethernet bridge with tap interface added
~~~
root@polly:~# brctl show
bridge name	bridge id		STP enabled	interfaces
virbr0		8000.525400e83d3c	yes		tap0
							virbr0-nic
~~~

- Dosemu configured to use tap
~~~
$_pktdriver=(on)                                                                
$_vnet = "tap"                                                                  
$_tapdev = "tap0"                                                               
~~~

- NWClient's STARTNET.BAT file using Packet Driver to ODI shim and the following NET.CFG
##### NET.CFG
~~~
Link Driver NE2000                                                              
        PORT 300                                                                
        IRQ 3                                                                   
        FRAME Ethernet_802.2                                                    
                                                                                
Link Driver PDEther                                                             
        INT 60                                                                  
                                                                                
Link Support                                                                    
        Buffers 4 1514                                                          
                                                                                
NetWare DOS Requester                                                           
        FIRST NETWORK DRIVE = H                                                 
        NETWARE PROTOCOL = NDS BIND                                             
~~~
##### STARTNET.BAT
~~~
SET NWLANGUAGE=ENGLISH                                                          
C:\NWCLIENT\LSL.COM                                                             
                                                                                
rem C:\NWCLIENT\NE2000.COM                                                      
C:\pdether\pdether                                                              
                                                                                
C:\NWCLIENT\IPXODI.COM                                                          
C:\NWCLIENT\VLM.EXE                                                             
~~~

![vlm-crash](https://user-images.githubusercontent.com/220835/61594389-2fd62500-abe3-11e9-8375-17739bf7d770.png)

The terminal that started dosemu shows this
~~~
ajb@polly:/clients/common/dosemu2.git$ ./runstandalonetest.sh
ERROR: fdpp booting, this is very experimental!
MCB corruption
ERROR: fdpp: abort at memmgr.cc:328
~~~

And the log file with debug 'f' is here 
[vlm-crash.zip](https://github.com/stsp/fdpp/files/3414841/vlm-crash.zip)

**Comment by stsp** [comment]
Damn, comcom32 bug...

**Comment by andrewbird** [comment]
Thing is I'm seeing this with Freecom, perhaps there are two bugs?

**Comment by stsp** [comment]
Very likely...
But this is all I could reproduce.

**Comment by stsp** [comment]
Works very well for me now.
Please open another ticket if this is still a problem.

**Comment by stsp** [comment]
And if you do, please make sure the MCB
of command.com is self-owned.

**Comment by stsp** [comment]
I mean, with comcom32 it crashed for me
even under freedos. So this definitely had
to be fixed before anything else.

**Comment by andrewbird** [comment]
Here's FreeCOM's MCB, you can see the owner is itself so I think that's all good
~~~
dosdebug> mcbs
dosdebug> 

ADDR(LOW) PARAS  OWNER
0291:0000 0x0536 [DOS]
  => ADDR      PARAS TYPE USAGE
     0292:0000 0x000c [F] Files
     029f:0000 0x0008 [D] Driver (EMUFS)
     02a8:0000 0x0009 [D] Driver (EMS)
     02b2:0000 0x029e [B] Buffers
     0551:0000 0x0154 [F] Files
     06a6:0000 0x008f [L] CDS Array
     0736:0000 0x0080 [S] Stacks
     07b7:0000 0x0010 [B] Buffers
07c8:0000 ------ [LINK]
0871:0000 0x0006 [FREE]
0878:0000 0x00bc [COMMAND]
0935:0000 0x000f [04371]
0945:0000 0x0306 [LSL]
0c4c:0000 0x00b5 [PDETHER]
0d02:0000 0x040f [IPXODI]
1112:0000 0x015f [VLM]
1272:0000 0x77ef [04371]
8a62:0000 0x058c [04371]
8fef:0000 0x0fff [FREE]
9fef:0000 0x0010 [COMMAND] (END)
dosdebug> d 0878:0000
dosdebug> 

0878:0000 4D 79 08 BC 00 00 00 00 43 4F 4D 4D 41 4E 44 00  My.<....COMMAND.

0878:0010 CD 20 06 1C 00 9A C0 00 00 00 0C 0A 89 08 25 F1  M ....@.......%q
0878:0020 00 F0 EF 0F D9 00 79 08 01 01 01 00 02 FF FF FF  .po.Y.y......
0878:0030 FF FF FF FF FF FF FF FF FF FF FF FF F0 9F 7E 08  p.~.
0878:0040 89 08 14 00 18 00 79 08 00 00 60 00 00 00 00 00  ......y...`.....
0878:0050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0878:0060 CD 21 CB 00 00 00 00 00 00 00 00 00 00 20 20 20  M!K..........   
0878:0070 20 20 20 20 20 20 20 20 00 00 00 00 00 20 20 20          .....   
~~~

I'm going to stop pursuing this as I've pretty much forgotten why I was trying this network client anyway. Unfortunately I use this machine for private stuff so I can't open it to the Internet, so let's leave it unresolved and perhaps a better test case will present itself sometime.

**Comment by stsp** [comment]
Can anyone else still reproduce that, even
with the fixed comcom32?

**Comment by stsp** [comment]
Built with `-m32` and still no crash.
So this is not a 32bit-specific.
Could you please upload a self-contained test-case?

**Comment by andrewbird** [comment]
Here's what I have [nwtest.tar.gz](https://github.com/stsp/comcom32/files/3453383/nwtest.tar.gz)

1/ cd nwclient
2/ startnet
3/ Crash on VLM load of NETX.VLM

**Comment by stsp** [comment]
Reproduced.

**Comment by stsp** [comment]
So the crash happens because of your
`dos=low,noumb` which is not in a default
config. I am shocked you haven't told me
that for over a week...

**Comment by andrewbird** [comment]
The `dos=low,noumb` is an artefact from the experiment you asked me to do in https://github.com/stsp/comcom32/issues/27#issuecomment-514112569. Before I had no `dos=`, would that equate to noumb?

**Comment by stsp** [comment]
> I had no dos=, would that equate to noumb?

Of course!

**Comment by stsp** [comment]
Please, test with the default setup first,
otherwise this is getting ridiculously time-consuming
every now and then.

**Comment by andrewbird** [comment]
>>    I injured my back again, so I can't sit for long periods

> fdpp is not worth the health!
So please get well. :)
I'll take the care of it while you are away.

Thanks (back still isn't right yet, but not terrible pain like it was!), and thanks for fixing this issue in https://github.com/stsp/fdpp/issues/96, VLM loads all modules successfully for me now.

**Comment by stsp** [comment]
Good but now I can't fix the build on LP
(and can't reproduce the problem).
Any help is appreciated.
What kind of a back problem, some prolapse?

**Comment by andrewbird** [comment]
> Good but now I can't fix the build on LP
(and can't reproduce the problem).

I think that indicates some make parallelism issue, I'll have a look, but it's unlike I'll be able to reproduce either.

>  What kind of a back problem, some prolapse?

Not sure, never had it professionally looked at, as it usually gets better with just std pain killers and avoidance of triggers. On one occasion when it was prolonged I had a deep tissue massage which fixed it for me, though for 3 days immediately afterwards I felt like I'd been beaten up!

**Comment by andrewbird** [comment]
Isn't the `configure -> fdppconf.hh` step failing because of this?
~~~
make[3]: Entering directory '/<<PKGBUILDDIR>>/build/src/plugin/fdpp'
fatal: not a git repository (or any of the parent directories): .git
Non-git builds deprecated
make[3]: Leaving directory '/<<PKGBUILDDIR>>/build/src/plugin/fdpp'
~~~

**Comment by stsp** [comment]
I usually do the MRI scan when something like
that happens. It may (or may not) tell you the exact
cause of the problem (likely won't, unless you present
the scans to the doctor), but for sure will tell you
the overall picture (literally) of the current state
of affairs, and can be easily compared to what it
was a few years ago (helps for bisecting the regressions).

> Isn't the configure -> fdppconf.hh step failing because of this?

Because of what exactly? Non-git repository?
That shouldn't matter I suppose. And besides, it shouldn't
even proceed to compile fdpp.o before compiling all its
pre-requisites. For some reason it doesn't count fdppconf.hh
as a pre-requisite and goes straight to fdpp.o.

**Comment by andrewbird** [comment]
> Because of what exactly? Non-git repository?

That's odd in itself as the repo is git now.

**Comment by stsp** [comment]
I want to re-fix this parent_psp problem
differently. For example I can create a
"secondary" PSP which will have the
correct parent, leaving the self-parented
PSP inactive.
But I suspect that terminating from
secondary PSP is not much better
than with the wrong parent, as this
will lead to some problems too, like
the memory leaks.
@ecm-pushbx what do you think?
Can some trick with creating the
secondary PSP free us from the need
of restoring parent at exit?
