### ISSUE TITLE
Using comcom32 breaks custom setup with 'drive_c'

### ISSUE THREAD

**Issue by bolle732** [stsp/comcom32#3]
When I have activated `comcom32` (together with `fdpp`), I cannot start anymore my custom setup, which has the files too in a folder named `drive_c`, as the default under `~/.dosemu`.

Error message:
`ERROR: Bootable drive not found, exiting`

Renaming either `~/.dosemu/drive_c` or `~/<CUSTOM>/drive_c` to another name makes it work again.

The custom setup use this to start DOSEMU2:
`/usr/local/bin/dosemu.bin --Fimagedir $G_DOSEMU_HOME -f $G_DOSEMU_HOME/dosemurc $@`

Would it be better to check for boot files in the provided paths first and then if not found check in the default paths ?

**Comment by bolle732** [comment]
In `dosemurc` I have specified:

`$_hdimage = "./drive_c"`

**Comment by stsp** [comment]
Yes, but its better to have this ticket in dosemu2.
comcom32 does not define the boot sequence.

**Comment by bolle732** [comment]
Ok, I'll close this ticket and open another one in dosemu2.
