### ISSUE TITLE
Exitemu

### ISSUE THREAD

**Issue by ZoccoCss** [stsp/comcom32#33]
**Describe the bug**
I updated to the latest version and ran a dos accounting program from a desktop icon. When I exited the program I noticed that dosemu didn't close and a message that said  `Bad command or filename - exitemu`

It used to happen that when I exited the program I also exited dosemu automatically. 

I also checked with a game and the same thing happened. 

**To Reproduce**
Steps to reproduce the behaviour:

Run dosemu and a program with the -E parameter

**Attach the binaries**
No binaries needed

**Attach the log**
Attached
[boot.log.gz](https://github.com/stsp/dosemu2/files/3515871/boot.log.gz)

**Comment by stsp** [comment]
Should now be fixed.

**Comment by stsp** [comment]
Of course it didn't have anything to do with
any game you run, but just with `-K` option.

**Comment by ZoccoCss** [comment]
Excelent.
