### ISSUE TITLE
Command line tail in PSP is not same as MSDOS or DRDOS

### ISSUE THREAD

**Issue by andrewbird** [stsp/comcom32#34]
Printing the PSP from MSDOS 6.22 or DRDOS 7.01 shows the command line tail is prefixed with a space, whereas on FDPP with comcom32 it is not. Changing to use Freecom under FDPP gives a similar result to MS/DR DOS.

### MS-DOS 6.22
~~~
122f:0080 05 20 54 45 53 54 0D 53 45 4D 55 5F 56 45 52 53  . TEST.SEMU_VERS
~~~

### FDPP/Freecom from FreeDOS 1.20
~~~
1cc1:0080 05 20 54 45 53 54 0D 00 32 35 36 0D 0A 00 00 00  . TEST..256.....
~~~

### FDPP/comcom32
~~~
0f09:0080 04 54 45 53 54 0D 50 05 08 00 00 01 08 05 00 02  .TEST.P.........
~~~

**Comment by stsp** [comment]
Is this a problem of djgpp libc?
Does it cause any troubles?

**Comment by andrewbird** [comment]
Mmm I'm not sure about libc, if it is I don't think I'll pursue it as I'm only looking for FDPP/Dosemu problems.

> Does it cause any troubles?

Not any proper ones that I know of. I'm seeing it only because a wrote a test in the test suite to validate certain PSP fields after int21/26. If you think it's okay for it to be different I can make the test more lax and close this issue?

**Comment by stsp** [comment]
I think I was wrong about libc.
Applied the completely untested patch,
please see if it does the trick.

**Comment by andrewbird** [comment]
Thanks, the test passes now.
