### ISSUE TITLE
Crash under FreeDOS

### ISSUE THREAD

**Issue by andrewbird** [stsp/comcom32#5]
I just compiled comcom32 from git using djgpp
~~~
ajb@polly:/clients/common/comcom32.git$ /opt/djgpp/bin/i586-pc-msdosdjgpp-gcc --version
i586-pc-msdosdjgpp-gcc (GCC) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
~~~

I then copied it over the stock FreeDOS 1.20 command.com and tried to boot Dosemu2, but I see this crash

![comcom32-freedos1 20](https://user-images.githubusercontent.com/220835/48725835-55122e00-ec25-11e8-870c-81ef3c9c6d26.png)

**Comment by stsp** [comment]
Come on, this is not from git.
I have disabled this silly djgpp
banner long ago.

**Comment by andrewbird** [comment]
Ignore this, there was an old 'command.exe' in the build directory that wasn't cleaned up with make clean. It works fine with comcom32.exe
